import{a as m,i as c,S as f}from"./assets/vendor-vwbIfzmB.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();function g(r){return m.get("https://pixabay.com/api/",{params:{key:"50312672-6ff896f2a2c8f700d68e76dd9",q:r,image_type:"photo",orientation:"horizontal",safesearch:"true"}}).then(a=>a.data.hits.length===0?(c.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",titleColor:"white",messageColor:"white"}),[]):a.data.hits.map(t=>(console.log("hit:",t),{webformatURL:t.webformatURL,largeImageURL:t.largeImageURL,tags:t.tags,likes:t.likes,views:t.views,comments:t.comments,downloads:t.downloads})))}const p=document.querySelector(".gallery"),y=document.querySelector(".form"),n=document.querySelector(".input");y.addEventListener("submit",r=>{r.preventDefault();const a=n.value.trim();if(a.length===0){c.warning({message:"Будь ласка, введіть запит",position:"topRight",backgroundColor:"rgb(255, 0, 34)",titleColor:"white",messageColor:"white"});return}L(),w(),g(a).then(t=>{h(t),l()}).catch(t=>{console.error("Помилка при завантаженні зображень:",t),l()}),n.value=""});function h(r){p.innerHTML=r.map(({webformatURL:t,largeImageURL:s,tags:e,likes:o,views:i,comments:u,downloads:d})=>`
        <li class="gallery-item">
        <a href="${s}" alt="${e}">
        <img src="${t}"
        alt="${e}"
        title="Likes: ${o} | Views: ${i} | Comments: ${u} | Downloads: ${d}"
        />
        </a>
        </li>`).join(""),new f(".gallery a",{captions:!0,captionsData:"title",captionDelay:250,captionPosition:"bottom",captionClass:""}).refresh()}function L(){const r=document.querySelector(".gallery");r.innerHTML=""}function w(){document.querySelector(".loader").classList.add("is-visible")}function l(){document.querySelector(".loader").classList.remove("is-visible")}
//# sourceMappingURL=index.js.map
