import{a as d,i as l,S as m}from"./assets/vendor-vwbIfzmB.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();function f(r){return d.get("https://pixabay.com/api/",{params:{key:"50312672-6ff896f2a2c8f700d68e76dd9",q:r,image_type:"photo",orientation:"horizontal",safesearch:"true"}}).then(i=>i.data.hits.length===0?(l.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",titleColor:"white",messageColor:"white"}),[]):i.data.hits.map(t=>(console.log("hit:",t),{webformatURL:t.webformatURL,largeImageURL:t.largeImageURL,tags:t.tags,likes:t.likes,views:t.views,comments:t.comments,downloads:t.downloads})))}const g=document.querySelector(".gallery"),p=document.querySelector(".form"),y=document.querySelector(".input");p.addEventListener("submit",r=>{r.preventDefault();const i=y.value.trim();if(i.length===0){l.warning({message:"Будь ласка, введіть запит",position:"topRight",backgroundColor:"rgb(255, 0, 34)",titleColor:"white",messageColor:"white"});return}L(),w(),f(i).then(t=>{h(t),n()}).catch(t=>{console.error("Помилка при завантаженні зображень:",t),n()})});function h(r){g.innerHTML=r.map(({webformatURL:t,largeImageURL:a,tags:e,likes:o,views:s,comments:c,downloads:u})=>`
      <li class="gallery-item">
        <a href="${a}">

          <img src="${t}"
          alt="${e}"
          title="Likes: ${o} | Views: ${s} | Comments: ${c} | Downloads: ${u}"
          />
        </a>
      </li>`).join(""),new m(".gallery a",{captions:!0,captionsData:"title",captionDelay:250,captionPosition:"bottom",captionClass:""}).refresh()}function L(){const r=document.querySelector(".gallery");r.innerHTML=""}function w(){document.querySelector(".loader").classList.add("is-visible")}function n(){document.querySelector(".loader").classList.remove("is-visible")}
//# sourceMappingURL=index.js.map
